name: CI Build and Test

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build-and-test:
    uses: BHoM/GithubActions/.github/workflows/buildandtest.yml@develop
    with:
      repository_name: ${{ github.repository }}
      branch_name: ${{ github.head_ref || github.ref_name }}
      dotnet_version: '6.0.x'
      build_configuration: 'Release'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
